// Login
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS"; 

// Teacher
export const GET_TEACHERS_SUCCESS = "GET_TEACHERS_SUCCESS";
export const TEACHER_CREATE_SUCCESS = "TEACHER_CREATE_SUCCESS";
export const TEACHER_UPDATE_SUCCESS = "TEACHER_UPDATE_SUCCESS";
export const TEACHER_DELETE = "TEACHER_DELETE";
export const TEACHER_DELETE_SUCCESS = "TEACHER_DELETE_SUCCESS";
export const TEACHER_DELETE_FAILED = "TEACHER_DELETE_FAILED";

// User

export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS";

// Student 

export const STUDENT_CREATE_SUCCESS = "STUDENT_CREATE_SUCCESS";  
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS"; 
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";

// Lesson

export const GET_ALL_LESSONS_SUCCESS = "GET_ALL_LESSONS_SUCCESS"; 
export const GET_LESSON_BY_ID = "GET_LESSON_BY_ID";
export const GET_LESSON_BY_USER_ID = "GET_LESSON_BY_USER_ID";
export const GET_NOT_OWNED_LESSONS_BY_USER_ID = "GET_NOT_OWNED_LESSONS_BY_USER_ID";
export const GET_LESSON_WITHOUT_TEACHER = "GET_LESSON_WITHOUT_TEACHER";
export const GET_STUDENT_BY_LESSON = "GET_STUDENT_BY_LESSON";
export const GET_TEACHER_BY_LESSON =  "GET_TEACHER_BY_LESSON";
export const GET_LESSON_DOCUMENTS = "GET_LESSON_DOCUMENTS";



// Homework

export const GET_HOMEWORKS_BY_LESSON_ID = "GET_HOMEWORKS_BY_LESSON_ID";
export const GET_HOMEWORKS_BY_ID = "GET_HOMEWORKS_BY_ID";
export const UPDATE_HOMEWORK_BY_ID = "UPDATE_HOMEWORK_BY_ID";  
export const GET_HOMEWORK_DEADLINE_BOOLEAN = "GET_HOMEWORK_DEADLINE_BOOLEAN";
export const GET_HOMEWORK_DOCUMENTS = "GET_HOMEWORK_DOCUMENTS";
export const GET_ALL_STUDENT_HOMEWORK_BT_HOMEWORK_ID = "GET_ALL_STUDENT_HOMEWORK_BT_HOMEWORK_ID";
export const CHECK_STUDENT_HOMEWORK = "CHECK_STUDENT_HOMEWORK"; 